[DATA]
num_records = 1000000
raw_data_path = data/raw/retail_sales_raw.csv
chunk_size = 100000

[LOGGING]
log_folder = log
log_file = data_generation.log

[MINIO]
# Localhost container ke andar kaam nahi karta, isliye service name use karein
endpoint = http://minio:9000
access_key = admin
secret_key = password123
bucket_name = warehouse